### ISSUE TITLE
Error running tuya-cli list-app

### ISSUE THREAD

**Issue by mikecay** [codetheweb/tuyapi#110]
Hi, when I run tuya-cli list-app in get the following error.

`/home/xxxxx/.nvm/versions/node/v6.14.4/lib/node_modules/@tuyapi/cli/lib/link.js:7
async function link(config, options) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/xxxxx/.nvm/versions/node/v6.14.4/lib/node_modules/@tuyapi/cli/cli.js:9:14)
`

I'm running on Ubuntu 16.04.  Any help would be appreciated.

Mike

**Comment by codetheweb** [comment]
Looks like your Node version is too old.  Please update Node to >= 8.0.0 and try again.

**Comment by mikecay** [comment]
That worked.  Thank you.

**Comment by codetheweb** [comment]
👍
