### ISSUE TITLE
TypeError: tmp.length is not a function

### ISSUE THREAD

**Issue by johannes87** [codetheweb/tuyapi#128]
I get this error when I try to run the asynchronous example program from codetheweb/tuyapi.

I use node v11.6.0

```
~/c/tuyatest » node index.js
/Users/johannes/coding/tuyatest/node_modules/node-forge/lib/aes.js:203
    var len = tmp.length();
                  ^

TypeError: tmp.length is not a function
    at forge.aes.Algorithm.initialize (/Users/johannes/coding/tuyatest/node_modules/node-forge/lib/aes.js:203:19)
    at new forge.cipher.BlockCipher (/Users/johannes/coding/tuyatest/node_modules/node-forge/lib/cipher.js:118:18)
    at Object.forge.cipher.createCipher (/Users/johannes/coding/tuyatest/node_modules/node-forge/lib/cipher.js:42:10)
    at new TuyaCipher (/Users/johannes/coding/tuyatest/node_modules/tuyapi/lib/cipher.js:14:30)
    at new TuyaDevice (/Users/johannes/coding/tuyatest/node_modules/tuyapi/index.js:117:26)
    at Object.<anonymous> (/Users/johannes/coding/tuyatest/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
```

`index.js`:

```
const TuyAPI = require('tuyapi');

const device = new TuyAPI({
  id: 'XXXXXXXX',
  key: 'XXXXXXX',
  ip: '192.168.1.181',
  persistentConnection: true});

device.on('connected',() => {
  console.log('Connected to device.');
});

device.on('disconnected',() => {
  console.log('Disconnected from device.');
});

device.on('data', data => {
  console.log('Data from device:', data);

  const status = data.dps['1'];

  console.log('Current status:', status);

  device.set({set: !status}).then(result => {
    console.log('Result of setting status:', result);
  });
});

device.on('error',(err) => {
  console.log('Error: ' + err);
});

device.connect();

// Disconnect after 10 seconds
setTimeout(() => { device.disconnect(); }, 10000);
```

**Comment by codetheweb** [comment]
Does the synchronous example work?

**Comment by cryptoe** [comment]
https://github.com/digitalbazaar/forge/issues/552
Your key needs to be of len 16/32 .

**Comment by codetheweb** [comment]
Closing this because of inactivity, feel free to reopen @johannes87 if you're still having problems.
