### ISSUE TITLE
Issue running the code even after getting the device id and key

### ISSUE THREAD

**Issue by divyaran7an** [codetheweb/tuyapi#201]
I've been trying since a week now to get this script to work and I don't know why but I've not been able to make any progress. I have a smart plug that can be controlled through the Smart Life app or the TuySmart app. 
I have followed all the instructions correctly and was able to get the device id and the key but still when I run the script with the correct id and the key I've been getting errors. 
My index.js consists of the following code : - 

`
const TuyAPI = require('tuyapi');

const device = new TuyAPI({
  id: '214XXXXXXXXXXXXX',
  key: '5dXXXXXXXXXXXX'
});

let stateHasChanged = false;

device.find().then(() => {
  // Connect to device
  device.connect();
});

device.on('connected', () => {
  console.log('Connected to device!');
});

device.on('disconnected', () => {
  console.log('Disconnected from device.');
});

device.on('error', error => {
  console.log('Error!', error);
});

device.on('data', data => {
  console.log('Data from device:', data);
  console.log(`Boolean status of default property: ${data.dps['1']}.`);

  if (!stateHasChanged) {
    device.set({set: !(data.dps['1'])});
    stateHasChanged = true;
  }
});
setTimeout(() => { device.disconnect(); }, 10000);
`

Once I run this I'm getting the following error: 
`
Home$ node index.js
(node:27122) UnhandledPromiseRejectionWarning: Error: find() timed out. Is the device powered on and the ID or IP correct?
    at pTimeout (/Users/Home/tuyapi-divya/node_modules/tuyapi/index.js:572:13)
    at Timeout.setTimeout [as _onTimeout] (/Users/Home/tuyapi-divya/node_modules/p-timeout/index.js:20:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:27122) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27122) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I'm running this on a macbook with node 6.4.1 installed and I've been trying for days to get this to work but getting the same error. Any help from the community would be appreciated!

**Comment by divyaran7an** [comment]
@codetheweb what do you think?

**Comment by codetheweb** [comment]
Sometimes network configurations can result in devices not being found.

Try passing in an IP to the constructor and see if it works.  If not, start your script with `DEBUG=* node xxx.js` and post the output.

**Comment by divyaran7an** [comment]
I tried passing in an ip to the constructor and this is what I am getting - 
`
Home$ DEBUG=* node index.js
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 106.51.74.145... +5ms
(node:36233) UnhandledPromiseRejectionWarning: Error: connection timed out
    at Socket.client.setTimeout (/Users/Home/tuyapi/node_modules/tuyapi/index.js:305:18)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:440:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:36233) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36233) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  TuyAPI Socket closed: 106.51.74.145 +5s
Disconnected from device.
  TuyAPI Disconnect +5s
`

**Comment by divyaran7an** [comment]
@codetheweb there is this option on my Tuya smart app for testing network connection. Whenever I'm taking the test it says Failed. Attached the screenshot. Is this related? My device info also doesn't show me a private ip for the device. 

![IMG_0810](https://user-images.githubusercontent.com/2841689/58330937-9e05a200-7e55-11e9-8a0c-70bb0f346978.PNG)
![IMG_0809](https://user-images.githubusercontent.com/2841689/58330938-9e05a200-7e55-11e9-991a-bbce1b3b6971.PNG)
![IMG_0808](https://user-images.githubusercontent.com/2841689/58330939-9e9e3880-7e55-11e9-8e7a-50b91aebad63.PNG)

**Comment by codetheweb** [comment]
Is your device on a different network or subnet?  Looks like both your phone and your computer can't communicate with it locally.

**Comment by divyaran7an** [comment]
> Is your device on a different network or subnet? Looks like both your phone and your computer can't communicate with it locally.

Maybe. What can I do to change this? I remember before adding the plug I had this option to connect with my home wifi and I did that. How can I get my device to be on the same network?

**Comment by codetheweb** [comment]
It should be on the same network if that's what you did.

Are you able to log into your router's interface and see the assigned IP?  Just looked at a previous post and realized you passed the WAN IP of your network rather than the LAN IP of the plug.

**Comment by codetheweb** [comment]
Closing this because of inactivity.

If you're still seeing issues, please comment and I'll reopen it.

**Comment by beans14** [comment]
@codetheweb could i use the mac address?

**Comment by codetheweb** [comment]
Not sure what you're asking. Please open a new issue with additional details if you still need help.
