### ISSUE TITLE
Physical switch toggle breaks data callback

### ISSUE THREAD

**Issue by coryallegory** [codetheweb/tuyapi#229]
Observed using tuyapi v5.1.1 commit `c72cda1`
My device is a Prime Smart Plug/Outlet, Model CCRCWFII113PK
Vendor Firmware 1.0.6

Using boilerplate code:
```
device.on('data', (data) => {
  console.log('Data from device:', data);
  console.log(`Boolean status of default property: ${data.dps['1']}.`);
});
```
works accurately and as expected upon connection, or calling `.get()`
When device's physical switch is toggled, callback returns unexpected `data` parameter.

When switching "off":
```
Data from device: 3.15da6cd7ae98dec92ULuuPlNDvsHIGBrPP/pv13Adp6OkWjY9ienz6BgscXsEm4C48s5olsvuc0fEeo91F6+1acBvXmFfvNspgye5/nHwr73An3CDMxa4yVc4+bc=
C:\Development\tuyapp\app.js:43
  console.log(`Boolean status of default property: ${data.dps['1']}.`);
                                                             ^
TypeError: Cannot read property '1' of undefined
    at TuyaDevice.device.on (C:\Development\tuyapp\app.js:43:62)
    at emitThree (events.js:136:13)
    at TuyaDevice.emit (events.js:217:7)
    at TuyaDevice._packetHandler (C:\Development\tuyapp\node_modules\tuyapi\index.js:414:10)
    at packets.forEach.packet (C:\Development\tuyapp\node_modules\tuyapi\index.js:315:43)
    at Array.forEach (<anonymous>)
    at Socket.client.on.data (C:\Development\tuyapp\node_modules\tuyapi\index.js:311:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

When switching "on":
```
Data from device: 3.12865aade877406d0ULuuPlNDvsHIGBrPP/pv13Adp6OkWjY9ienz6BgscXvHlaDSWYy5gNJNrRUjjZlXWRdGic/uPkbe4iUOyrJVNH3nNY0DHfeQE36G0BcpxLY=
C:\Development\tuyapp\app.js:43
  console.log(`Boolean status of default property: ${data.dps['1']}.`);
                                                             ^
TypeError: Cannot read property '1' of undefined
    at TuyaDevice.device.on (C:\Development\tuyapp\app.js:43:62)
    at emitThree (events.js:136:13)
    at TuyaDevice.emit (events.js:217:7)
    at TuyaDevice._packetHandler (C:\Development\tuyapp\node_modules\tuyapi\index.js:414:10)
    at packets.forEach.packet (C:\Development\tuyapp\node_modules\tuyapi\index.js:315:43)
    at Array.forEach (<anonymous>)
    at Socket.client.on.data (C:\Development\tuyapp\node_modules\tuyapi\index.js:311:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

**To Reproduce**
1. Implement event callback as above, and as documented.
2. Toggle physical switch on device
3. See error

**Expected behavior**
Expecting to see duplicate callback output as takes place when device is initially connected
e.g.
```
Data from device: { devId: '22014508600194c312ec', dps: { '1': true, '9': 0 } }
Boolean status of default property: true.
```

**Debug Output**

```
$ DEBUG=* node app.js
  express:router:route new '/' +0ms
  express:router:layer new '/' +2ms
  express:router:route get '/' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +1ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +1ms
  express:router:layer new '/' +0ms
  TuyAPI Finding missing IP undefined or ID 22014508600194c312ec +0ms
  express:application set "x-powered-by" to true +19ms
  express:application set "etag" to 'weak' +0ms
  express:application set "etag fn" to [Function: generateETag] +1ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryStri
ng] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +1ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to 'C:\\Development\\tuyapp\\views' +1ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:application set "views" to 'C:\\Development\\tuyapp\\views' +0ms
  express:application set "view engine" to 'jade' +1ms
  express:router use '/' query +1ms
  express:router:layer new '/' +1ms
  express:router use '/' expressInit +0ms
  express:router:layer new '/' +1ms
  express:router use '/' logger +1ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +1ms
  express:router:layer new '/' +1ms
  express:router use '/' urlencodedParser +1ms
  express:router:layer new '/' +1ms
  express:router use '/' cookieParser +0ms
  express:router:layer new '/' +0ms
  express:router use '/' serveStatic +1ms
  express:router:layer new '/' +1ms
  express:router use '/' router +1ms
  express:router:layer new '/' +0ms
  express:router use '/users' router +1ms
  express:router:layer new '/users' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +1ms
  TuyAPI Received UDP message. +1s
  TuyAPI UDP data: +9ms
  TuyAPI { payload:
  TuyAPI    { ip: '192.168.137.156',
  TuyAPI      gwId: '22014508600194c312ec',
  TuyAPI      active: 2,
  TuyAPI      ability: 0,
  TuyAPI      mode: 0,
  TuyAPI      encrypt: true,
  TuyAPI      productKey: 'key5nck4tavy43jp',
  TuyAPI      version: '3.1' },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 0,
  TuyAPI   sequenceN: 0 } +1ms
  TuyAPI Connecting to 192.168.137.156... +8ms
  TuyAPI Socket connected. +5ms
Connected to device!
  TuyAPI GET Payload: +2ms
  TuyAPI { gwId: '22014508600194c312ec', devId: '22014508600194c312ec' } +0ms
  TuyAPI Received data: 000055aa000000010000000a00000043000000007b22646576496422
3a223232303134353038363030313934633331326563222c22647073223a7b2231223a747275652c
2239223a307d7d3ae81d700000aa55 +10ms
  TuyAPI Parsed: +2ms
  TuyAPI { payload: { devId: '22014508600194c312ec', dps: { '1': true, '9': 0 }
},
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1 } +0ms
Data from device: { devId: '22014508600194c312ec', dps: { '1': true, '9': 0 } }
Boolean status of default property: true.
  TuyAPI GET Payload: +3ms
  TuyAPI { gwId: '22014508600194c312ec', devId: '22014508600194c312ec' } +0ms
  TuyAPI Received data: 000055aa000000020000000a00000043000000007b22646576496422
3a223232303134353038363030313934633331326563222c22647073223a7b2231223a747275652c
2239223a307d7d95aeb5160000aa55 +6ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: { devId: '22014508600194c312ec', dps: { '1': true, '9': 0 }
},
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 2 } +1ms
Data from device: { devId: '22014508600194c312ec', dps: { '1': true, '9': 0 } }
Boolean status of default property: true.
  TuyAPI Received data: 000055aa00000000000000080000008b00000000332e316135373339
6634353935336663663861554c7575506c4e447673484947427250502f70763133416470364f6b57
6a593969656e7a36426773635873456d3443343873356f6c73767563306645656f39314c67304f53
506e374e4443334b51624b42412b6341424650767654387a74747a67556b30645a3666396a633d83
28404c0000aa55 +5s
  TuyAPI Parsed: +4ms
  TuyAPI { payload: '3.1a5739f45953fcf8aULuuPlNDvsHIGBrPP/pv13Adp6OkWjY9ienz6Bgs
cXsEm4C48s5olsvuc0fEeo91Lg0OSPn7NDC3KQbKBA+cABFPvvT8zttzgUk0dZ6f9jc=',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 8,
  TuyAPI   sequenceN: 0 } +2ms
Data from device: 3.1a5739f45953fcf8aULuuPlNDvsHIGBrPP/pv13Adp6OkWjY9ienz6BgscXs
Em4C48s5olsvuc0fEeo91Lg0OSPn7NDC3KQbKBA+cABFPvvT8zttzgUk0dZ6f9jc=
C:\Development\tuyapp\app.js:43
  console.log(`Boolean status of default property: ${data.dps['1']}.`);
                                                             ^

TypeError: Cannot read property '1' of undefined
    at TuyaDevice.device.on (C:\Development\tuyapp\app.js:43:62)
    at emitThree (events.js:136:13)
    at TuyaDevice.emit (events.js:217:7)
    at TuyaDevice._packetHandler (C:\Development\tuyapp\node_modules\tuyapi\inde
x.js:414:10)
    at packets.forEach.packet (C:\Development\tuyapp\node_modules\tuyapi\index.j
s:315:43)
    at Array.forEach (<anonymous>)
    at Socket.client.on.data (C:\Development\tuyapp\node_modules\tuyapi\index.js
:311:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version 8.9.3

**Comment by Apollon77** [comment]
It seems that for some reason the response payload could not be decrypted ... @kueblc

**Comment by kueblc** [comment]
Would you share your `localKey`? You can send it to me privately if you wish by my gmail of the same name.

**Comment by kueblc** [comment]
Did you try `set()`? It may be an incorrect `localKey`.

**Comment by coryallegory** [comment]
I've been using my device's `productKey` rather than `localKey`, thanks for helping point me in the right direction!
https://github.com/codetheweb/tuyapi/blob/master/index.js#L26

Closing this issue
