### ISSUE TITLE
TuyaDevice.connect: UnhandledPromiseRejectionWarning at tuyapi/index.js:323:30.

### ISSUE THREAD

**Issue by derkallevombau** [codetheweb/tuyapi#255]
First of all, I would like to thank you for developing this API. Smart home devices I can't talk to directly are useless for me ;)

Most of the time, connecting takes < 1 sec and everythings works flawlessly, but since I'm developing a Node.js server that utilises your API, there are many `connect`s per day, and sometimes it get this error:

> /usr/bin/node tuyadevctlsrv.js 
> 2019-09-28 12:32:40.564  INFO Searching for device 'blindMid'...
> 2019-09-28 12:32:44.768  INFO Connecting to device 'blindMid'...
> (node:4672) UnhandledPromiseRejectionWarning: Error: Error from socket
>     at Socket.<anonymous> (/home/kalle/Node.js Projects/tuyadevctlsrv/node_modules/tuyapi/index.js:323:30)
>     at Socket.emit (events.js:209:13)
>     at errorOrDestroy (internal/streams/destroy.js:107:12)
>     at onwriteError (_stream_writable.js:443:5)
>     at onwrite (_stream_writable.js:470:5)
>     at doWrite (_stream_writable.js:424:11)
>     at writeOrBuffer (_stream_writable.js:412:5)
>     at Socket.Writable.write (_stream_writable.js:302:11)
>     at /home/kalle/Node.js Projects/tuyadevctlsrv/node_modules/tuyapi/index.js:232:23
>     at new Promise (<anonymous>)
> (node:4672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
> (node:4672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 

As you can see, I have tried everything to catch this error, with no luck:

```javascript
function connectDevices()
{
  ...
  
  const promises = [];
  
  for (let device of devices)
  {
    // Populate 'deviceFromName'

    device.commands = devCmdsFromType[device.type];
    device.api      = new TuyAPI(device.tuyapiCtorOpts);

    deviceFromName[device.name] = device;
  
    logger.info(`Searching for device '${device.name}'...`);
  
    try
    {
      const promise = device.api.find().then(
        found => 
        {
          if (found) // Do we need to check this? If 'found' was false, the 'rejected' handler should have been called instead.
          {
            logger.info(`Connecting to device '${device.name}'...`);
            
            try
            {
              return device.api.connect().then(
                connected => 
                {
                  if (connected) // Ditto.
                  {
                    connectedDeviceCount++;

                    logger.info(`Successfully connected to device '${device.name}'.`);

                    device.api.on('disconnected', () => logger.warn(`Event from device '${device.name}': Disconnected.`));
                    device.api.on('error', error => logger.error(`Event from device: '${device.name}': Error:`, error));
                    device.api.on('data', data => onDeviceData(device, data));
                  }
                  else logger.error(`Could not connect to device '${device.name}'.`);
                },
                connectErr => logger.error(`Could not connect to device '${device.name}':`, connectErr)
              );
            }
            catch (e) { logger.error('connectDevices (connect): Catched: ', e); }
          }
          else logger.error(`Device '${device.name}' not found.`);
        },
        findErr => logger.error(`Device '${device.name}' not found. Please make sure Tuya Smart Life App is CLOSED (not just in background), ` +
                    'you can use it again after we are connected to all devices.\nMessage from tuyapi:', findErr)
      );

      promises.push(promise);
    }
    catch (e) { logger.error('connectDevices (find): Catched: ', e); }
  }

  return Promise.all(promises);
}

...

// Main program

if (readConfig())
  connectDevices().then(
    () => 
    {
      if (connectedDeviceCount)
      {
        startServer();

        const connectedDevices = devices.filter(device => device.api.isConnected).map(device => device.name).join(', ');

        logger.info(`Successfully connected to ${connectedDeviceCount} of ${devices.length} devices: ${connectedDevices}.`);
      }
      else logger.error('Not going to start server because no devices could be connected.');
    },
    err => logger.error('Main program:', err)
  );
else process.exit(1);
```
The onrejected handler for `find` is invoked as expected. I can't remember if the one for `connect` has ever been invoked for a different kind of error, but at least not for that error.

**Comment by codetheweb** [comment]
The error you're getting is emitted as an event.

I think you need to move the `device.api.on` event handlers outside the `device.api.connect()` statement, since if the `connect()` function emits an error the error event handler doesn't have a chance to attach itself.

**Comment by codetheweb** [comment]
Closing because of inactivity.
