### ISSUE TITLE
bad decrypt

### ISSUE THREAD

**Issue by jwaes** [codetheweb/tuyapi#274]
```
 TuyAPI:mqtt receive settings {"topic":"tuya/bfec063d54cdd67b17pl4c/f616daa4e9521253/192.168.0.115/command","action":"command","message":"OFF","options":{"id":"bfec063d54cdd67b17pl4c","key":"f616daa4e9521253","ip":"192.168.0.115"}} +4m
  TuyAPI:device Search device in network +0ms
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI:device Device found in network +5ms
  TuyAPI Connecting to 192.168.0.115... +5ms
  TuyAPI Socket connected. +74ms
  TuyAPI:device Connected to device. undefined (192.168.0.115, bfec063d54cdd67b17pl4c, f616daa4e9521253) +78ms
  TuyAPI:device GET Payload: +2ms
  TuyAPI:device { gwId: 'bfec063d54cdd67b17pl4c',
  TuyAPI:device   devId: 'bfec063d54cdd67b17pl4c' } +0ms
  TuyAPI:mqtt receive command { set: false } +112ms
  TuyAPI:device set: { set: false } +25ms
  TuyAPI SET Payload: +30ms
  TuyAPI { devId: 'bfec063d54cdd67b17pl4c',
  TuyAPI   gwId: 'bfec063d54cdd67b17pl4c',
  TuyAPI   uid: '',
  TuyAPI   t: 1576360010,
  TuyAPI   dps: { '1': false } } +0ms
  TuyAPI Received response +14ms
  TuyAPI 000055aa000000000000000a0000002c00000001f20c3505b0769cef4574e55b5d9bc17a3c64dc51ec951ab920fc4d9687047cf3296c308d0000aa55 +1ms
  Cleanup Uncaught Exception... Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.final (internal/crypto/cipher.js:164:28)
    at TuyaCipher.decrypt (/etc/openhab2/scripts/tuyaapi_mqtt/node_modules/tuyapi/lib/cipher.js:65:24)
    at Socket.client.on.data (/etc/openhab2/scripts/tuyaapi_mqtt/node_modules/tuyapi/index.js:345:39)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) +0ms
  TuyAPI:device Disconnect from TuyAPI Device +24ms
  TuyAPI Disconnect +8ms
```

Any idea what might be cuasing this Exception ?

**Comment by codetheweb** [comment]
I would try setting the device version to 3.3 and see if that fixes the issue.

You may also want to double check your `key` value (it changes every time you re-add your device in the Tuya app).

**Comment by jwaes** [comment]
Thanks, setting the version to 3.3 indeed helped me a step further. I can use SET and switch my device. But the GET still gives an error that other experience also. So i posted my comment in this thread:
https://github.com/codetheweb/tuyapi/issues/246#issuecomment-566235363
