### ISSUE TITLE
Access ID and key logic changed?

### ISSUE THREAD

**Issue by tehohosma** [codetheweb/tuyapi#295]
**Describe the bug**
Seems like Tuya has changed something in their Access ID / Authorization generation logic as the [SETUP.md](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md) guide does not seem to be working. I followed the guide and got my Cloud API authorization but the ID is like dq4nn8dvjftpsy4r8eug (len 20) and authorization key mj5e9yywcxud9w7d5uvjd7c5vjqprpnv (len 30); don't worry, these are already abolished in order to try re-applying.

Looking at the older issues I guess that the Access ID should be just numbers and authorization key shorter?

When I try to run the link code I just get this error:
tehohosma@HomeSRV:~$ sudo tuya-cli link --api-key dq4nn8dvjftpsy4r8eug --api-secret mj5e9yywcxud9w7d5uvjd7c5vjqprpnv --schema <nope> --ssid IoT --password <nope> --region eu
/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/index.js:7:18)
tehohosma@HomeSRV:~$ sudo tuya-cli link-wizard
/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/index.js:7:18)

**Comment by codetheweb** [comment]
Given that it's a syntax error, I'm guessing your Node version is too old.  Try upgrading to >= 12.0.0.

My API key and secret have a similar format.

**Comment by tehohosma** [comment]
I tried installing latest lts and succeeded in that but the end result remained the same.

For what it's worth I am running Ubuntu 18.04.4 lts.

$ npm version
{
  npm: '6.13.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.9.3',
  icu: '64.2',
  llhttp: '2.0.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.16.1',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.0',
  v8: '7.8.279.23-node.31',
  zlib: '1.2.11'
}

/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/index.js:7:18)/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/index.js:7:18)/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/index.js:7:18)/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/index.js:7:18)/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/index.js:7:18)/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/index.js:7:18)/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/index.js:7:18)

**Comment by codetheweb** [comment]
According to the maintainer of got (the source of the error), [that issue is due to an outdated Node version](https://github.com/sindresorhus/got/issues/1084).  Try running `node -v` to double check the version of Node?  Might be different than what NPM reports for some reason.

**Comment by tehohosma** [comment]
Node -v outputs the same result as well. I wonder if my node is somehow broken.

$ node -v                                                                                                      v12.16.1

**Comment by codetheweb** [comment]
You could try editing `/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/create.js` manually and just adding `console.log(process.version)` at the top of the file to see what Node version is running it.

**Comment by tehohosma** [comment]
I did that and ran tuya-cli. Print out was v12.16.1.

I have a spare rpi lying around so I guess I should try with that as well.

**Comment by tehohosma** [comment]
I tested it with fresh rpi. Outcome was lot better although I didn't do the linking yet. Need to check the new access ids froom tuya first. I guess there is something wrong with the servers node.

✖ Device(s) failed to be registered!                                                                                              Error: sign invalid
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by tehohosma** [comment]
Yep, now it works. In principal I changed the machine from Ubuntu to (fresh) Raspberry PI, installed NodeJS manually, reinstalled it using NPM based on the documentation and then installed Tuya-cli using the SETUP.md guide. 

Thanks @codetheweb for help!

**Comment by codetheweb** [comment]
Glad it's working, not sure what the issue was.
