### ISSUE TITLE
Error: request time is invalid

### ISSUE THREAD

**Issue by matmat07** [codetheweb/tuyapi#307]
Hi, I've just tried running this on a fresh Kali linux install, and about less than a second after I run the command, I get this error message 

```
kali@kali:~$ sudo tuya-cli link --api-key REDACTED --api-secret REDACTED --schema REDACTED --ssid REDACTED --password REDACTED --region us
✖ Device(s) failed to be registered!
Error: request time is invalid
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```
Any idea what could be wrong? I wasn't getting that problem yesterday inside a docker on Unraid (which obviously wouldn't work as I found out the networking requirements).

**Comment by codetheweb** [comment]
Hmm, not sure what's going on. From a quick search it appears your time/date settings might be invalid on Kali? That can mess with SSL/TLS.
