### ISSUE TITLE
tuya-cli link permission deny

### ISSUE THREAD

**Issue by Fintasys** [codetheweb/tuyapi#313]
When I try to link a device I'm getting this error.
I tried to run it with `sudo` and give the folder full access but no success either. 
```
Error: permission deny
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**To Reproduce**
`sudo tuya-cli link --api-key xxxx --api-secret xxx --schema com.xxx --ssid wifi-xxxx --password xxxx --region cn`

**Expected behavior**
Register device

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Comment by Fintasys** [comment]
I forgot the step with "Obtain SDK".
