### ISSUE TITLE
Data Unreadable

### ISSUE THREAD

**Issue by marcopollacci** [codetheweb/tuyapi#314]
Hi! i've follow #297  issue, and then i've follow the #246 issue.
Pulled the  patch-json-error branch, but still the same issue in #297 .

"data M�뻋�������w�^���ߝRu$/%B�"
version 3.3

Any advice?

**Comment by marcopollacci** [comment]
after a little debug:

```
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.final (internal/crypto/cipher.js:170:29)
    at TuyaCipher.decrypt (/media/cerino/HDMIO/tuyaSmartNodejs/node_modules/tuyapi/lib/cipher.js:73:26)
    at MessageParser.getPayload (/media/cerino/HDMIO/tuyaSmartNodejs/node_modules/tuyapi/lib/message-parser.js:184:26)
    at MessageParser.parseRecursive (/media/cerino/HDMIO/tuyaSmartNodejs/node_modules/tuyapi/lib/message-parser.js:213:27)
    at MessageParser.parse (/media/cerino/HDMIO/tuyaSmartNodejs/node_modules/tuyapi/lib/message-parser.js:232:26)
    at Socket.<anonymous> (/media/cerino/HDMIO/tuyaSmartNodejs/node_modules/tuyapi/index.js:315:42)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
}
```
```
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.final (internal/crypto/cipher.js:170:29)
    at TuyaCipher.decrypt (/media/cerino/HDMIO/tuyaSmartNodejs/node_modules/tuyapi/lib/cipher.js:80:28)
    at MessageParser.getPayload (/media/cerino/HDMIO/tuyaSmartNodejs/node_modules/tuyapi/lib/message-parser.js:184:26)
    at MessageParser.parseRecursive (/media/cerino/HDMIO/tuyaSmartNodejs/node_modules/tuyapi/lib/message-parser.js:213:27)
    at MessageParser.parse (/media/cerino/HDMIO/tuyaSmartNodejs/node_modules/tuyapi/lib/message-parser.js:232:26)
    at Socket.<anonymous> (/media/cerino/HDMIO/tuyaSmartNodejs/node_modules/tuyapi/index.js:315:42)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
}
```

**Comment by codetheweb** [comment]
Have you confirmed that the `key` parameter is correct (it changes every time you relink it / add it to the app)?

That's usually the root cause for bad decrypts.

**Comment by marcopollacci** [comment]
Hi ! Yes, i take this value, after pair it

  device: {
    ip: '<ip>',
    port: 6668,
    id: '<id>',
    gwID: '<gwID>',
    **key: '13101cdb44ba6a5f', <---**
    productKey: undefined,
    version: 3.3,
    parser: MessageParser {
      version: '3.3',
      cipher: [TuyaCipher],
      **key: '13101cdb44ba6a5f' <---**
    }
  },

i'm doing it right?

**Comment by codetheweb** [comment]
Yep, that's passed in correctly.

Can you re-run whatever script you're testing with prefixed with `DEBUG=*` (assuming you're on *nix) and post the output?

**Comment by codetheweb** [comment]
Closing because of inactivity.
