### ISSUE TITLE
tuya-cli set --set true gives unhandled error event

### ISSUE THREAD

**Issue by cdprince** [codetheweb/tuyapi#337]
**Describe the bug**
I used tuya-cli to set my smart power switch and based on another issue, 113, used the same syntax, "--set true", and resulted in an Unhandled 'error' event.

I then tried the same command, but instead used "--set True" and the command worked fine.

**To Reproduce**
pi@raspberrypi:~/git/tuyapi $ DEBUG=* tuya-cli set --ip "10.0.0.212" --id 73328546dc4f******** --key **************** --dps 2 --set true
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 10.0.0.212... +11ms
  TuyAPI Socket connected. +21ms
  TuyAPI GET Payload: +3ms
  TuyAPI { gwId: '73328546dc4f22e*****',
  TuyAPI   devId: '73328546dc4f22******',
  TuyAPI   t: '1592941738',
  TuyAPI   dps: {},
  TuyAPI   uid: '73328546dc4f22e*****' } +1ms
  TuyAPI SET Payload: +22ms
  TuyAPI { devId: '73328546dc4f22******',
  TuyAPI   gwId: '73328546dc4f22******',
  TuyAPI   uid: '',
  TuyAPI   t: 1592941737,
  TuyAPI   dps: { '2': true } } +0ms
  TuyAPI Error event from socket. 10.0.0.212 { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +14ms
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Error from socket
    at Socket.client.on.err (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:350:30)
    at Socket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:614:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:791:10)
Emitted 'error' event at:
    at Socket.client.on.err (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:350:16)
    at Socket.emit (events.js:198:13)
    [... lines matching original stack trace ...]
    at WriteWrap.afterWrite [as oncomplete] (net.js:791:10)

**Expected behavior**
I would imagine an error message, or filter to perform equally well using "true" as "True", I assumed "false" would have the same issue, but it did not.  Easy fix?

**Debug Output**
done

**Screenshots**
n/a

**Desktop (please complete the following information):**
pi@raspberrypi:~/git/tuyapi $ uname -a
Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
pi@raspberrypi:~/git/tuyapi $ node -v
v10.21.0

**Additional context**
n/a

**Comment by codetheweb** [comment]
🤔 are you able to consistently reproduce this with `true`?
That debug output is showing the correct payload being sent.

**Comment by pabigot** [comment]
Might be related to TuyaAPI/cli#75.

**Comment by codetheweb** [comment]
Confirmed bug: https://github.com/TuyaAPI/cli/issues/75.

Thanks @pabigot.

**Comment by codetheweb** [comment]
@cdprince a patch was just pushed thanks to @pabigot. Please upgrade to @1.13.3 and see if that fixes your issue.

**Comment by codetheweb** [comment]
Closing because of inactivity.
