### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by rleinfellner** [codetheweb/tuyapi#341]
installed with npm i @tuyapi/cli -g

Ran tuya-cli wizard

Got
/home/richard/.npm-global/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/richard/.npm-global/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/index.js:7:18)

Any help would be appriciated as I am stuck now

**Comment by rleinfellner** [comment]
Found it was an issue with node.js install, once that was fixed it worked
