### ISSUE TITLE
Can't extract the key with tuya-cli

### ISSUE THREAD

**Issue by jpcanovas** [codetheweb/tuyapi#349]
Hello, I'm triying to get the key of a plug using tuya cli. 
First i add the device to the Tuya Smart App (v3.19.4). From the app I can control the plug. I can turn it on and off and i can see the power consumption. 

So I try the process "Listing Tuya devices from the app": I create iot.tuya.com account,  create the fake app and launch tuya-cli. Input for the api key, input for the api secret, and inpuit for the device id (which i extract from TuyaSmart app). But then the only answer is "There was an issue fetching that device. Make sure your account is linked and the ID is correct."

Of course the api-key, api-secret are correct (checked several times witrh the ones showed in iot.tuya.com).

I have tried to get debug messages launching the process as "DEBUG=* tuya-cli wizard", but nothing appears.

So, any idea?

PD. I have done the other process to get the key (using tuya-cli link) but I couldn0't get the key either. In this case ther message was
```

✖ Device(s) failed to be registered!
Error: data not exist
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by codetheweb** [comment]
It sounds like you might have missed steps 2-3:

> Go to Cloud Development -> select your application -> Project Overview -> Linked Device -> Link devices by App Account.
> Click 'Add App Account' and scan the QR code from your app (go to the 'Me' tab, and there's a QR code button in the upper right).

**Comment by jpcanovas** [comment]
Hi, no, i Did that step. But I 've re-readed the steps and I have foudn something about the name of the packet of the app (should start with "com."). Mine doesn't start with "com", so that could be the reason?

**Comment by TroyG-Aus** [comment]
I'm having a similar problem. Installed tuya-cli (within the embedded terminal of my Homebridge instance, which is installed on a Synology via package+docker). Created a Tuya IOT account. Created a project. Linked via QR. Copied/pasted the API + Secret Key + Device ID (the one listed right below the name). I'm also getting the error:

`There was an issue fetching that device. Make sure your account is linked and the ID is correct.`

The only difference I see between what I see and Tech with Eddie's video ( https://youtu.be/oq0JL_wicKg ) is my devices are located in Europe (myself I'm located in Australia) - which I had to select in the dropdown to get the Device ID. Safe assumption the wizard traverses all possible geographies?

If there are any commands I can run to help debug, please let me know. Thx!

**Comment by ronitsinha** [comment]
Same issue here in the US-- so @TroyG-Aus it doesn't seem Australia-specific. I've tried using `tuya-cli wizard` as well as `tuya-cli link`; neither seem to work (I get the same errors as seen above).

**Comment by codetheweb** [comment]
> Safe assumption the wizard traverses all possible geographies?

@TroyG-Aus yes, as long as you have the most recent version (v1.13.3).

Are you guys using the official TuyaSmart app, or a white labeled version?

**Comment by ronitsinha** [comment]
I tried both the official TuyaSmart app and SmartLife-- no luck either way, unfortunately.

**Comment by TroyG-Aus** [comment]
Yup, v1.13.3, and using the official TuyaSmart app v3.19.2.

**Comment by codetheweb** [comment]
I just published a new version, v1.13.14. It will now log the API error if the environment variable DEBUG is set to * (`DEBUG=* tuya-cli wizard` on *sh).

Can you please update, try again, and post the specific error you're getting?

**Comment by jpcanovas** [comment]
Well. i have tried right now with v1.13.14 and It worked. It has returned the name i gave in the app, and more important, the key.

I haven't change anything, so i wonder if it could be something related with servers updating in the Tuya part or something like that.

Anyway, thanks for the help.

**Comment by codetheweb** [comment]
Huh, glad it's working now.

I'm closing this for now, if it's still not working for @ronitsinha or @TroyG-Aus let me know and I can reopen it.

**Comment by jpcanovas** [comment]
By the way. Is this normal or maybe i stikll have a problem?

`
DEBUG=* tuya-cli get --all --ip 192.168.1.107 --id bf0cf1c337dba9cc2***** --key ***************
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.1.107... +6ms
  TuyAPI Socket connected. +103ms
  TuyAPI GET Payload: +2ms
  TuyAPI {
  TuyAPI   gwId: 'bf0cf1c337dba9cc2*****',
  TuyAPI   devId: 'bf0cf1c337dba9cc2*****',
  TuyAPI   t: '1598887409',
  TuyAPI   dps: {},
  TuyAPI   uid: 'bf0cf1c337dba9cc2*****'
  TuyAPI } +0ms
  TuyAPI GET Payload: +10ms
  TuyAPI {
  TuyAPI   gwId: 'bf0cf1c337dba9cc2*****',
  TuyAPI   devId: 'bf0cf1c337dba9cc2*****',
  TuyAPI   t: '1598887409',
  TuyAPI   dps: {},
  TuyAPI   uid: 'bf0cf1c337dba9cc2*****'
  TuyAPI } +0ms
  TuyAPI Received data: 000055aa000000010000000a0000002c00000001308d53879b489fb2b8f6433c1e82ff5af06d29b297020c964a1e6d8319e66650c7aaa6310000aa55 +29ms
  TuyAPI Parsed: +3ms
  TuyAPI {
  TuyAPI   payload: 'parse data error',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1
  TuyAPI } +0ms
  TuyAPI Received data: 000055aa000000020000000a0000002c00000001308d53879b489fb2b8f6433c1e82ff5af06d29b297020c964a1e6d8319e66650f861d8a40000aa55 +336ms
  TuyAPI Parsed: +0ms
  TuyAPI {
  TuyAPI   payload: 'parse data error',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 2
  TuyAPI } +1ms
  TuyAPI Disconnect +0ms
parse data error
  TuyAPI Socket closed: 192.168.1.107 +4ms
`

**Comment by TroyG-Aus** [comment]
Very weird results here as well... But it ultimately worked... Steps I did this AM...

Note that prior to my original post, just to make sure I followed every step, I created a new Tuya Cloud Development Project - we'll call it Project 2 - and linked my lights to that. My first post was my results from Project 2.

1. Ran v.1.13.3 again to see if it was a server issue. But ran it against Project 1. Same Result
2. Updated to v.1.13.4
3. Ran v.1.13.4 in DEBUG against Project 1. Results were...
```
/homebridge # DEBUG=* tuya-cli wizard
? The API key from tuya.com: xxxxdyxxxxflyjanxxxx
? The API secret from tuya.com xxxx86075bf04dcxxxxf4f74b652xxxx
? Provide a 'virtual ID' of a device currently registered in the app: xxxx067xxxxf22b9xxxx
AggregateError: Every promise rejected
    at new AggregateError (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/es-aggregate-error/implementation.js:18:14)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:38:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:69:29) {
  errors: [
    Error: data not exist
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: data not exist
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: data not exist
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ]
}
There was an issue fetching that device. Make sure your account is linked and the ID is correct.
```
4. Ran v.1.13.4 in DEBUG against Project 2. Aaaaaaannnnd it worked!

Comparing the two projects showed no difference, so I'm also wondering if it was a weird server related issue specific to when projects were created? **SHRUG** Anyway, all good on this end. Thank you so much for your help @codetheweb

**Comment by ronitsinha** [comment]
Hooray! With the new update it's working for me! Actually had a similar setup to @TroyG-Aus. I had 2 projects: when I tried with the first one it didn't work (I got the same error as @TroyG-Aus), but the second one was successful. Really weird. HUGE THANKS @codetheweb, you are amazing.

**Comment by codetheweb** [comment]
Interesting, glad it's working now.
Sounds like it was/is an issue on Tuya's side.

**Comment by realjax** [comment]
Have the same problem. I tried with several projects but the result is always the same:

There was an issue fetching that device. Make sure your account is linked and the ID is correct.

Debug tells me I don't have acces to the API??

```
{ AggregateError: Every promise rejected
    at new AggregateError (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/es-aggregate-error/implementation.js:18:14)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:38:10
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  errors:
   [ Error: you don't have access to this API
         at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
         at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
         at processTicksAndRejections (internal/process/next_tick.js:81:5),
     Error: you don't have access to this API
         at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
         at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
         at processTicksAndRejections (internal/process/next_tick.js:81:5),
     Error: you don't have access to this API
         at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
         at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
         at processTicksAndRejections (internal/process/next_tick.js:81:5) ] }
There was an issue fetching that device. Make sure your account is linked and the ID is correct.
```

I thought the API key and secret are the ones listed here or is that not correct?

![Screenshot 2020-09-03 at 15 40 17](https://user-images.githubusercontent.com/883435/92122614-f159f480-edfb-11ea-96e5-c14db1dd6f34.png)

**Comment by realjax** [comment]
Created a new project and although I now seem to have acces, I get this instead:

```
 [ Error: data not exist
         at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
         at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
         at processTicksAndRejections (internal/process/next_tick.js:81:5),
     Error: data not exist
         at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
         at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
         at processTicksAndRejections (internal/process/next_tick.js:81:5),
     Error: data not exist
         at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
         at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
         at processTicksAndRejections (internal/process/next_tick.js:81:5) ] }
```

I'm on  v.1.13.4 by the way...

**Comment by thomveen** [comment]
i still have a error;

`AggregateError: Every promise rejected
    at new AggregateError (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/es-aggregate-error/implementation.js:18:14)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:38:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:69:29) {
  errors: [
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ]
}`

Live in Holland
Device Europe

**Comment by thomveen** [comment]
i still have a error;

`AggregateError: Every promise rejected
    at new AggregateError (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/es-aggregate-error/implementation.js:18:14)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:38:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:69:29) {
  errors: [
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ]
}`

Live in Holland
Device Europe

**Comment by thomveen** [comment]
i still have a error;

`AggregateError: Every promise rejected
    at new AggregateError (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/es-aggregate-error/implementation.js:18:14)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:38:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:69:29) {
  errors: [
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ]
}`

Live in Holland
Device Europe 
v 1.13.4

**Comment by thomveen** [comment]
i still have a error;

`AggregateError: Every promise rejected
    at new AggregateError (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/es-aggregate-error/implementation.js:18:14)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:38:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:69:29) {
  errors: [
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ]
}`

Live in Holland
Device Europe 
v 1.13.4

**Comment by thomveen** [comment]
i still have a error;

`AggregateError: Every promise rejected
    at new AggregateError (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/es-aggregate-error/implementation.js:18:14)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:38:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:69:29) {
  errors: [
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ]
}`

Live in Holland
Device Europe 
v 1.13.4

**Comment by thomveen** [comment]
i still have a error;

`AggregateError: Every promise rejected
    at new AggregateError (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/es-aggregate-error/implementation.js:18:14)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:38:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:69:29) {
  errors: [
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ]
}`

Live in Holland
Device Europe 
v 1.13.4

**Comment by thomveen** [comment]
i still have a error;

`AggregateError: Every promise rejected
    at new AggregateError (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/es-aggregate-error/implementation.js:18:14)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:38:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:69:29) {
  errors: [
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ]
}`

Live in Holland
Device Europe 
v 1.13.4

**Comment by realjax** [comment]
@thomveen Had that too, create a new project and see if that one gives you access..

It seems Tuya's cloud crap is just that..

**Comment by thomveen** [comment]
@realjax i tried but it doesn't work

**Comment by javiermarasco** [comment]
Also can confirm from Holland is still not working, did create a new project, added my devices all but still get the "You don't have access to this API" message.

AggregateError: Every promise rejected
    at new AggregateError (/usr/lib/node_modules/@tuyapi/cli/node_modules/es-aggregate-error/implementation.js:18:14)
    at /usr/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:38:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async list (/usr/lib/node_modules/@tuyapi/cli/lib/wizard.js:69:29) {
  errors: [
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5),
    Error: you don't have access to this API
        at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
        at EventEmitter.<anonymous> (/usr/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ]
}

Also using version 1.3.4.

Very strange indeed

**Comment by codetheweb** [comment]
@javiermarasco please try the solution in this issue: https://github.com/codetheweb/tuyapi/issues/351

**Comment by javiermarasco** [comment]
@codetheweb digging a bit in tuya.com found that "API Group" tab and after a few clicks it worked, I was coming back to happily post the solution haha.

Thank you for pointing in the right direction, that definitely solves the issue.

**Comment by jeff-h** [comment]
Thanks @javiermarasco for the suggestion. I had changed the status to Open for all the seven API Groups and they all went "Open" but when I double-checked that page I found one of them was no longer Open. I re-applied it, and it went green again. I then re-ran the `tuya-cli wizard` command and it failed yet again. However after about a minute or two I tried it again and it worked!

**Comment by NW27** [comment]
Hi,
I'm trying to run "tuya-cli wizard" on a raspberry pi but I'm getting the below debug response.
How do you give access to the API on a Pi?


[
  Error: you don't have access to this API
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
      at EventEmitter.<anonymous> (/usr/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  Error: you don't have access to this API
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
      at EventEmitter.<anonymous> (/usr/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  Error: you don't have access to this API
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
      at EventEmitter.<anonymous> (/usr/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
]

**Comment by codetheweb** [comment]
@NW27:

The step to get API authorization is done on Tuya's website, not your Pi. Please follow the [setup instructions](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md); and open a new issue if you still have questions.

**Comment by sunn78** [comment]
> @NW27:
> 
> The step to get API authorization is done on Tuya's website, not your Pi. Please follow the [setup instructions](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md); and open a new issue if you still have questions.

Please,  can you explain step by step how do it, in tuya I can't see how run the command.

**Comment by codetheweb** [comment]
> Please, can you explain step by step how do it, in tuya I can't see how run the command.

I'm sorry; I'm not really sure what you mean by this. Please open a new issue with additional details if you still need help.
