### ISSUE TITLE
Can't extract the key with tuya-cli

### ISSUE THREAD

**Issue by realjax** [codetheweb/tuyapi#351]
When using tuya-cli to get the key, using `tuya-cli wizard`. the output is always:

`There was an issue fetching that device. Make sure your account is linked and the ID is correct.`

running `DEBUG=* tuya-cli wizard`. returns this:

```
{ AggregateError: Every promise rejected
    at new AggregateError (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/es-aggregate-error/implementation.js:18:14)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:38:10
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  errors:
   [ Error: you don't have access to this API
         at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
         at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
         at processTicksAndRejections (internal/process/next_tick.js:81:5),
     Error: you don't have access to this API
         at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
         at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
         at processTicksAndRejections (internal/process/next_tick.js:81:5),
     Error: you don't have access to this API
         at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
         at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
         at processTicksAndRejections (internal/process/next_tick.js:81:5) ] }
```

But I am  sure the api key and secret used are the right ones ( the ones from the newly created project).  Could it be that newly created projects are not accessible right away (anymore) ?

**To Reproduce**
1. create a new project on https://iot.tuya.com/
2. Then use the new api key and secret with 'tuya-cli wizard'
3. See error

**Comment by tomporter518** [comment]
I have added 4 new devices and I am having the same issue even though I'm fairly confident I followed the set up instructions correctly. My debug output looks the same, `Error: you don't have access to this API`.

**Comment by tomporter518** [comment]
I was able to get the wizard method to function by going into Cloud Development -> My Project -> API Setting and opening Authorization Management, Device Management & Device Control.

**Comment by realjax** [comment]
> I was able to get the wizard method to function by going into Cloud Development -> My Project -> API Setting and opening Authorization Management, Device Management & Device Control.

Nope. didnt work for me.  I even 'opened up' ( click 'apply' and then give some bogus reason if you feel like it) everything but still no cigar..  :(

**Comment by WilliamRandol** [comment]
> I was able to get the wizard method to function by going into Cloud Development -> My Project -> API Setting and opening Authorization Management, Device Management & Device Control.

This did work for me thanks a ton!

**Comment by TempestWales** [comment]
> > I was able to get the wizard method to function by going into Cloud Development -> My Project -> API Setting and opening Authorization Management, Device Management & Device Control.
> 
> Nope. didnt work for me. I even 'opened up' ( click 'apply' and then give some bogus reason if you feel like it) everything but still no cigar.. :(

Did you open up all 21 items? As there's a second page. Took me 20 minutes to notice.

![image](https://user-images.githubusercontent.com/10633668/92313190-c1a81980-efc0-11ea-8463-4a2b18e7f3a6.png)

**Comment by tomporter518** [comment]
> Did you open up all 21 items?

I started slowly. I only opened Authorization Management & Device Control at first. That was not enough. I also added then Device Management (based on its description). Once I did that, it worked and continues to work for me.

One thing to ensure is that your phone/tablet application is linked.

**Comment by apauly** [comment]
> I was able to get the wizard method to function by going into Cloud Development -> My Project -> API Setting and opening Authorization Management, Device Management & Device Control.

It seems that you have to wait several minutes after activating these. At least for me, directly after enabling the APIs I still got the same error, but after 5-10 minutes I got the desired result

**Comment by realjax** [comment]
Yep, succes!  Waited a few days and indeed it worked. Thanks a ton everyone!

**Comment by codetheweb** [comment]
Closing this for now.

**Comment by codetheweb** [comment]
Setup docs have been updated: https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md.

**Comment by briggitteorellana** [comment]
Hello. The api key and api secret where I get them???

**Comment by Frank-Bemelman** [comment]
Just to confirm that I also had the problems as mentioned. After creating the account at iot.tuya.com you really need to wait. In my case even a few hours was not enough, but the next day, some 12 hours later, everything worked flawless. They key seems to wait rather than trying all sorts of silly moves. Thanks a lot for this great integration!

**Comment by OllyWelch** [comment]
With debug enabled I get the following error - has anyone else had this particular message/know why this could be?

`TypeError: Promise.all called on non-object
    at all (<anonymous>)
    at Function.any (/usr/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:29:9)
    at any (/usr/lib/node_modules/@tuyapi/cli/node_modules/promise.any/index.js:16:9)
    at list (/usr/lib/node_modules/@tuyapi/cli/lib/wizard.js:70:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
There was an issue fetching that device. Make sure your account is linked and the ID is correct.
`

**Comment by codetheweb** [comment]
@OllyWelch please follow https://github.com/codetheweb/tuyapi/issues/432 for updates.
