### ISSUE TITLE
SET command doesn't resolve and loops until force quit (doesn't update device)

### ISSUE THREAD

**Issue by ReggiePeters** [codetheweb/tuyapi#352]
I can successfully connect my wifi plug, but I can't pass commands or read states with get. 

I've successfully connected my device (a "JINVOO Wifi Smart Plug" from amazon) on both my iot.Tuya.com account and through the console on my raspberry pi (4 B running ARM7l) using tuya-cli wizard and, independently, tuya-cli link. The output from these are the same, with the exception that the tuya-cli wizard command does not return the ip.

```
✔ Device(s) registered!
[
  {
    id: 'XXXXXXX',
    ip: '75.164.XX.XX,
    localKey: 'XXXXXXXX'
    name: 'WiFi Plug   '
  }
]
```

This ip address threw an error when used for either 'get' or 'set' commands:
```
Error: connection timed out
    at Socket.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:302:18)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:482:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

If I omit the IP address in a 'set' command, it returns: 
```
(node:16494) UnhandledPromiseRejectionWarning: Error: Error from socket
    at Socket.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:350:30)
    at Socket.emit (events.js:315:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at doWrite (_stream_writable.js:399:11)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:242:23
    at new Promise (<anonymous>)
(node:16494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:16494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16494) UnhandledPromiseRejectionWarning: Error: Error from socket
    at Socket.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:350:30)
    at Socket.emit (events.js:315:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at doWrite (_stream_writable.js:399:11)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:242:23
    at new Promise (<anonymous>)
(node:16494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
```

If I omit the IP in a 'get' command it returns:
```
TypeError: Cannot read property '1' of undefined
    at Object.get (/usr/local/lib/node_modules/@tuyapi/cli/lib/control.js:56:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I took a look at my router to confirm that it was using 2.4GHz (it is) and dropped my firewall to make sure it wasn't being blocked (it wasn't) and then grabbed the IP for the wall socket under the connected devices. I used that IP instead and now get the below when I use the 'set' command:
```
 throw er; // Unhandled 'error' event
      ^

Error: Error from socket
    at Socket.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:350:30)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on TuyaDevice instance at:
    at Socket.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:350:16)
    at Socket.emit (events.js:315:20)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Am I missing something? I can successfully control the wifi plug from the tuya app (besides testing I otherwise shut off the app so it isn't potentially interfering).

Thanks for any help you can offer.

**Comment by codetheweb** [comment]
Can you try running your script / tuya-cli with debug mode on by setting the environment variable `DEBUG=*` (`DEBUG=* tuya-cli ...` on *sh) and post the output here?

**Comment by ReggiePeters** [comment]
I used the debug mode with the GET command while excluding the IP address and realized that I had been using the wrong IP in my original post. I meant to use the _other_ device connected to my router that I don't recognize (I should figure out what the first one was). As a quick aside, this still isn't the IP address returned when first linking the device (which was a 75.XXX number).

So while I no longer get the unhandled error event, when I try and SET the state of my device it never resolves. I apologize for the confusion. I really thought I had tried that IP as well.

When I run the SET command in debug mode I get the following output. It never resolves with the last 5 lines repeating, the only variation coming from the speed of the received data.
```
pi@raspberrypi:~ $ DEBUG=* tuya-cli set --ip 192.XXX.X.XX --id 'XXXXXXXXXXXXXXXXXXX' --key 'XXXXXXXXXXXXXXXXXXX' --set 'true' *sh
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.XXX.X.XX... +6ms
  TuyAPI Socket connected. +103ms
  TuyAPI GET Payload: +2ms
  TuyAPI {
  TuyAPI   gwId: 'XXXXXXXXXXXXXXXXXXX'
  TuyAPI   devId: 'XXXXXXXXXXXXXXXXXXX'
  TuyAPI   t: '1600053261',
  TuyAPI   dps: {},
  TuyAPI   uid: 'XXXXXXXXXXXXXXXXXXX'
  TuyAPI } +0ms
  TuyAPI SET Payload: +13ms
  TuyAPI {
  TuyAPI   devId: 'XXXXXXXXXXXXXXXXXXX'
  TuyAPI   gwId: 'XXXXXXXXXXXXXXXXXXX'
  TuyAPI   uid: '',
  TuyAPI   t: 1600053260,
  TuyAPI   dps: { '1': true }
  TuyAPI } +0ms
  TuyAPI Pinging 192.XXX.X.XX +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +39ms
  TuyAPI Parsed: +4ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 192.XX.X.XX +1ms
  TuyAPI Pinging 192.XX.X.XX +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +2s
  TuyAPI Parsed: +2ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 192.XXX.X.XX+2ms
```
So the lines that repeat are:
```
  TuyAPI Pinging 192.XX.X.XX +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +2s
  TuyAPI Parsed: +2ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 192.XXX.X.XX+2ms
```

When I run the GET command in debug mode and excluding the IP address I get this output:
```pi@raspberrypi:~ $ DEBUG=* tuya-cli get --id XXXXXXXXXXXXXXXXXXX --key XXXXXXXXXXXXXXXXXXX *sh
  TuyAPI Finding missing IP undefined or ID XXXXXXXXXXXXXXXXXXX +0ms
  TuyAPI Received UDP message. +3s
  TuyAPI UDP data: +10ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     ip: '192.XXX.X.XX'
  TuyAPI     gwId: 'XXXXXXXXXXXXXXXXXXX',
  TuyAPI     active: 2,
  TuyAPI     ability: 0,
  TuyAPI     mode: 0,
  TuyAPI     encrypt: true,
  TuyAPI     productKey: 'jutTAkekSaIvLkun',
  TuyAPI     version: '3.3'
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 19,
  TuyAPI   sequenceN: 0
  TuyAPI } +0ms
  TuyAPI Connecting to 192.XXX.X.XX... +20ms
  TuyAPI Socket connected. +80ms
  TuyAPI GET Payload: +2ms
  TuyAPI {
  TuyAPI   gwId: 'XXXXXXXXXXXXXXXXXXX',
  TuyAPI   devId: 'XXXXXXXXXXXXXXXXXXX',
  TuyAPI   t: '1600052559',
  TuyAPI   dps: {},
  TuyAPI   uid: 'XXXXXXXXXXXXXXXXXXX'
  TuyAPI } +0ms
  TuyAPI GET Payload: +7ms
  TuyAPI {
  TuyAPI   gwId: 'XXXXXXXXXXXXXXXXXXX'
  TuyAPI   devId: 'XXXXXXXXXXXXXXXXXXX',
  TuyAPI   t: '1600052559',
  TuyAPI   dps: {},
  TuyAPI   uid: 'XXXXXXXXXXXXXXXXXXX'
  TuyAPI } +1ms
  TuyAPI Received data: 000055aa000000010000000a0000004c0000000027a5729578ee400173a8f0106ca2b4a2e7a953f72d855ac3948d7fa48f50f8a9ea3f4eeaaaa7cbac8102c77d7a1ff8d9bf530ac98d4a23a618fb290af1e1857dfc0d23bd0000aa55 +31ms
  TuyAPI Parsed: +2ms
  TuyAPI {
  TuyAPI   payload: { devId: 'XXXXXXXXXXXXXXXXXXX', dps: { '1': false, '2': 0 } },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1
  TuyAPI } +0ms
  TuyAPI Received data: 000055aa000000020000000a0000004c0000000027a5729578ee400173a8f0106ca2b4a2e7a953f72d855ac3948d7fa48f50f8a9ea3f4eeaaaa7cbac8102c77d7a1ff8d9bf530ac98d4a23a618fb290af1e1857d654dc4d20000aa55 +25ms
  TuyAPI Parsed: +1ms
  TuyAPI {
  TuyAPI   payload: { devId: 'XXXXXXXXXXXXXXXXXXX', dps: { '1': false, '2': 0 } },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 2
  TuyAPI } +1ms
  TuyAPI Disconnect +1ms
false
  TuyAPI Socket closed: 192.XXX.X.XX+3ms
```
Running the GET command without debug mode returns "false"

**Comment by ReggiePeters** [comment]
After continuing to mess with debug mode, the protocol-versions and the updated IP apparently my commands are being successfully received. I thought I had tried this before, but clearly not. Sorry for taking your time, but thanks for helping.

**Comment by codetheweb** [comment]
👍 glad you got it working.
