### ISSUE TITLE
Device(s) failed to be registered!

### ISSUE THREAD

**Issue by adorobis** [codetheweb/tuyapi#370]
I have a problem discovering devices and connecting to Tuya cloud developer platform. I’m doing it from ubuntu server running as virtual machine on Windows laptop but the device, put in pairing mode is not being discovered. Should the tuya-cli be run only from physical machine in order to make it work?
I've also tried with raspberrypi running up to date version of Raspbian. Installed the tuya-cli but the effect is the same:
```
✖ Device(s) failed to be registered!
Error: Timed out waiting for devices to connect.
    at TuyaLinkWizard.linkDevice (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/index.js:117:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I'm trying with two types of switches: the Neo Coolcam WiFi Power Plug and "Wi-Fi Smart Switch Basic Tuya Smart". Both are properly discovered by Tuya mobile app and work ok.
Any hints on how to solve that?
Edit:
When trying to register using `tuya-cli wizard` I get a message: `There was an issue fetching that device. Make sure your account is linked and the ID is correct.`
Does it mean I have to link my Tuya Mobile app account with Tuya developer account? How to do that?

**Comment by adorobis** [comment]
Ah, I've missed the step in the manual to connect the App Account. Now the wizard works ok :)
