### ISSUE TITLE
list of drescription error

### ISSUE THREAD

**Issue by lle1904** [codetheweb/tuyapi#378]
Hi all,
I'm so newbie and I try to read all dps available on tuya socket energy monitor. 
I use a script describe in Issue 121 :

const TuyAPI = require('tuyapi');

const device = new TuyAPI({
  id: 'xxxxxxxxxxxxxxxxxxxx',
  key: 'xxxxxxxxxxxxxxxx',
  ip: 'xxx.xxx.xxx.xxx'});

device.get({schema: true}).then(data => {
  console.log(data);
});

When i run this, an error return this : 
lle@Mint19-VirtualBox:~$ node --trace-warnings tuyadevice.js
(node:5194) UnhandledPromiseRejectionWarning: Error: No connection has been made to the device.
    at TuyaDevice._send (/home/lle/node_modules/tuyapi/index.js:269:13)
    at /home/lle/node_modules/tuyapi/index.js:132:14
    at new Promise (<anonymous>)
    at TuyaDevice.get (/home/lle/node_modules/tuyapi/index.js:129:12)
    at Object.<anonymous> (/home/lle/tuyadevice.js:8:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:5194) Error: No connection has been made to the device.
    at TuyaDevice._send (/home/lle/node_modules/tuyapi/index.js:269:13)
    at /home/lle/node_modules/tuyapi/index.js:132:14
    at new Promise (<anonymous>)
    at TuyaDevice.get (/home/lle/node_modules/tuyapi/index.js:129:12)
    at Object.<anonymous> (/home/lle/tuyadevice.js:8:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
(node:5194) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

I think this script is depreced but i don't know what i write in script.

Thk for your return..

**Comment by kueblc** [comment]
> (node:5194) UnhandledPromiseRejectionWarning: Error: No connection has been made to the device.

You need to connect to the device before you can call anything on it. Check out the example in the README.

**Comment by lle1904** [comment]
all my device is connected and i have the local key with the installation instruction. The device connected in smartphone app and in Home assistant

**Comment by kueblc** [comment]
You should not have the device connected to the app or Home Assistant. You can only have one connection to it at a time. Please look at the example script in the README to learn how to connect to your device.

**Comment by lle1904** [comment]
i read the file, and the smart app is close. Home assistant is down

**Comment by kueblc** [comment]
If you read the README, then you should know you need to call `connect()` and wait for the `connected` event.

> const TuyAPI = require('tuyapi');
> 
> const device = new TuyAPI({
> id: 'xxxxxxxxxxxxxxxxxxxx',
> key: 'xxxxxxxxxxxxxxxx',
> ip: 'xxx.xxx.xxx.xxx'});
> 
> device.get({schema: true}).then(data => {
> console.log(data);
> });

Your script never calls `connect()` hence you are getting an error when you try to call `get()` on an unconnected device.

**Comment by kueblc** [comment]
Closing as resolved. If you still have questions after reading the documentation, feel free to reopen.

**Comment by lle1904** [comment]
So , i try with this script and the prblom is the same.. : 
lle@Mint19-VirtualBox:~$ node --trace-warnings tuyadevice.js
(node:6589) UnhandledPromiseRejectionWarning: Error: No connection has been made to the device.
    at TuyaDevice._send (/home/lle/node_modules/tuyapi/index.js:269:13)
    at /home/lle/node_modules/tuyapi/index.js:132:14
    at new Promise (<anonymous>)
    at TuyaDevice.get (/home/lle/node_modules/tuyapi/index.js:129:12)
    at Object.<anonymous> (/home/lle/tuyadevice.js:28:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:6589) Error: No connection has been made to the device.
    at TuyaDevice._send (/home/lle/node_modules/tuyapi/index.js:269:13)
    at /home/lle/node_modules/tuyapi/index.js:132:14
    at new Promise (<anonymous>)
    at TuyaDevice.get (/home/lle/node_modules/tuyapi/index.js:129:12)
    at Object.<anonymous> (/home/lle/tuyadevice.js:28:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
(node:6589) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
Connected to device!

sorry for the disturbed.

**Comment by codetheweb** [comment]
Can you please post your script?

It looks like you may not be waiting for the connection to your device to be established.
