### ISSUE TITLE
Wizard still gives 'Error: permission deny'

### ISSUE THREAD

**Issue by NicosKaralis** [codetheweb/tuyapi#387]
I'm trying to get the key and id of my device, but the API keeps giving me permission deny errors

1. ran ```DEBUG=* tuya-cli wizard```
2. Inserted my Project Authorization Keys (Access ID/Client ID and Access Secret/Client Secret)
3. Inserted the device ID
4. Then there is the error, ```Error: permission deny```

**Debug Output**

```
[
  Error: data not exist
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/Users/nicoskaralis/.nvm/versions/node/v13.8.0/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
      at EventEmitter.<anonymous> (/Users/nicoskaralis/.nvm/versions/node/v13.8.0/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  Error: data not exist
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/Users/nicoskaralis/.nvm/versions/node/v13.8.0/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
      at EventEmitter.<anonymous> (/Users/nicoskaralis/.nvm/versions/node/v13.8.0/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  Error: permission deny
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/Users/nicoskaralis/.nvm/versions/node/v13.8.0/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:73:31)
      at EventEmitter.<anonymous> (/Users/nicoskaralis/.nvm/versions/node/v13.8.0/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
]
There was an issue fetching that device. Make sure your account is linked and the ID is correct.
```

**Desktop (please complete the following information):**
 - OS macOS
 - OS Version 11.0.1
 - Node Version v13.8.0

I did follow the steps in the setup
I did linked the app with the platform ( I can see my device )
I did create an SDK app (even though I'm not using it right now)
I did wait 15 mins after enabling the API

What am I missing?

**Comment by codetheweb** [comment]
Since only one of those errors is associated with the correct region and the other two are not, my guess is that `permission deny` is the issue (as you pointed out).

If you did step 4 and opened all the required APIs, then it should work. It does seem to take longer than 15 minutes in some cases; maybe try again now?

**Comment by KTibow** [comment]
Which Tuya device are you using? Can you control it with the official Tuya app?
I'm running into this issue with some Sylvania Smart+ Yuya bulbs that only want to be controlled with their official app.

**Comment by codetheweb** [comment]
Closing because of inactivity.
