### ISSUE TITLE
tuya-cli link errors with "data not exist"

### ISSUE THREAD

**Issue by michaelzoellner** [codetheweb/tuyapi#388]
When I try to retrieve the parameters to control my device, tuya-cli link gives the following error:

```
✖ Device(s) failed to be registered!
Error: data not exist
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

When I modify api key or secret, I get a sign in error. Modifying the schema or Wifi data does not change the output. What might be wrong here? Schema was copied straight over from Tuya (App > App SDK > Development > Channel Identifier:).

**Comment by michaelzoellner** [comment]
I tried to use the tuya-cli link only because I got the error "There was an issue fetching that device" using the wizard. As the wizard did work now, I don't want to keep anyone busy with an error that I could by-pass.
