### ISSUE TITLE
@tuyapi/cli wizard broken

### ISSUE THREAD

**Issue by loglux** [codetheweb/tuyapi#411]
Put Key/Secret and Virtual ID but it doesn't seem working
```
There was an issue fetching that device. Make sure your account is linked and the ID is correct.
```

**Comment by loglux** [comment]
DEBUG
```
[ { GotError: Invalid value "undefined" for header "access_token"
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:200:27)
      at ClientRequest.setHeader (_http_outgoing.js:473:3)
      at new ClientRequest (_http_client.js:203:14)
      at Object.request (https.js:289:10)
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:197:65) name: 'RequestError', code: 'ERR_HTTP_INVALID_HEADER_VALUE' },
  { GotError: Invalid value "undefined" for header "access_token"
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:200:27)
      at ClientRequest.setHeader (_http_outgoing.js:473:3)
      at new ClientRequest (_http_client.js:203:14)
      at Object.request (https.js:289:10)
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:197:65) name: 'RequestError', code: 'ERR_HTTP_INVALID_HEADER_VALUE' },
  { GotError: Invalid value "undefined" for header "access_token"
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:200:27)
      at ClientRequest.setHeader (_http_outgoing.js:473:3)
      at new ClientRequest (_http_client.js:203:14)
      at Object.request (https.js:289:10)
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:197:65) name: 'RequestError', code: 'ERR_HTTP_INVALID_HEADER_VALUE' } ]
There was an issue fetching that device. Make sure your account is linked and the ID is correct.
root@DESKTOP-C1BDO16:~#

```

**Comment by maconic** [comment]
Exactly the same here :(

**Comment by codetheweb** [comment]
Tracking at https://github.com/TuyaAPI/openapi/issues/7.

**Comment by codetheweb** [comment]
This should be fixed now, please uninstall with `npm uninstall -g @tuyapi/cli` and re-install to get the updated dependency.

**Comment by loglux** [comment]
Good stuff. It's working now. 
I've managed to get keys
