### ISSUE TITLE
KeyError : 'Result'

### ISSUE THREAD

**Issue by spamoi33** [codetheweb/tuyapi#430]
Hello all,
I get this error after wizard. I'am on Debian 10 in VM. Can you help me please ?

root@debian:/home/franck# python3 -m tinytuya wizard                                                             TinyTuya Setup Wizard [1.2.1]

    Existing settings:
        API Key=xxx
        Secret=xxx
        DeviceID=xxx
        Region=eu

    Use existing credentials (Y/n): Y
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/tinytuya/__main__.py", line 48, in <module>
    tinytuya.wizard(color)
  File "/usr/local/lib/python3.7/dist-packages/tinytuya/__init__.py", line 1789, in wizard
    uid = response_dict['result']['uid']
KeyError: 'result'
root@debian:/home/franck#

**Comment by kueblc** [comment]
This is the issue tracker for the tuyapi project, an npm/JavaScript module.

It looks like you're looking for [tinytuya](https://github.com/jasonacox/tinytuya), a Python module. We have no affiliation with that project, but hopefully you can find what you're looking for by asking there.

**Comment by spamoi33** [comment]
Oupsss, sorry ...
