### ISSUE TITLE
Can't get tuya-cli wizard to work

### ISSUE THREAD

**Issue by schuesslerf** [codetheweb/tuyapi#432]
Hello,

I'm trying for two hours now to get the required data of my devices with the tuya-cli wizard...

What I did is: 
I registered at iot.tuya.com and created a project... There, I've got the "Access ID/Client ID" and the "Access Secret/Client Secret"..
Also, I connected my two devices with the Tuya Smart App. I can see both of them going to my project -> Device List and choosing "Europe" as region... 

Then, on my Raspberry pi, I'm using "sudo tuya-cli wizard" to start the wizard... For the API Key, I'm entering the "Access ID/Client ID" and for the API secret I'm entering the "Access Secret/Client Secret".. Then for "provide a 'virtual ID', I'm pasting on the Device ID's, that are listed at the device list in the first column...

Is everything I'm doing correct or I'm doing something wrong? Because after entering the 'virtual ID', I just get:
`There was an issue fetching that device. Make sure your account is linked and the ID is correct.`

What's the problem there, do you have any idea?

**Comment by schuesslerf** [comment]
Just to be sure to mention everything, I just tried to run with DEBUG argument, and am now getting this:

`TypeError: Promise.all called on non-object
    at all (<anonymous>)
    at Function.any (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:29:9)
    at any (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/index.js:16:9)
    at list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:70:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
There was an issue fetching that device. Make sure your account is linked and the ID is correct.
`

Propably it's an error with the code of the cli, not with the device registration itself?

**Comment by ZephyrChole** [comment]
Same problem

**Comment by britkat1980** [comment]
Seeing the same problem here. Two devices show up as linked in my cloud project at iot.tuya.com, but the cli returns "There was an issue fetching that device. Make sure your account is linked and the ID is correct."

**Comment by ZephyrChole** [comment]
Full output
TypeError: Promise.all called on non-object
    at all (<anonymous>)
    at Function.any (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:29:9)
    at any (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/index.js:16:9)
    at list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:70:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
There was an issue fetching that device. Make sure your account is linked and the ID is correct.

**Comment by FlyersPh9** [comment]
Same issue here:
```
TypeError: Promise.all called on non-object
    at all (<anonymous>)
    at Function.any (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:29:9)
    at any (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/index.js:16:9)
    at list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:70:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
There was an issue fetching that device. Make sure your account is linked and the ID is correct.
```

I have 2 devices listed online, pasting either device's ID # into the CLI results in this same error.

**Comment by FlyersPh9** [comment]
Update:  I never did get this working, but I did find an alternative route to get my Tuya device ID.  I followed the instructions in [this YouTube comment](https://www.youtube.com/watch?v=nIbCkYyZn6o&lc=UgymQckstw0RzIz9Q8N4AaABAg), installed the Chrome extension, restarted Chrome, enabled the extension, ran the tests, and then boom-- it works!

**Comment by ZephyrChole** [comment]
Okay,I have a solution.
My situation is that,I have a tuya socket and I want to control it with my raspberry pi.(If yours seems the same,look down)
Since I installed a software named "Home Assistant",things become much easier.
I added a plug-in named "tuya" in my HA,and logged in my tuya account.
As long as my raspi is in the same LAN with the socket,my raspi can control it.
As for automation,there's plenty of tutorial online.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jon Graft"<notifications@github.com&gt;; 
发送时间: 2021年3月7日(星期天) 凌晨5:46
收件人: "codetheweb/tuyapi"<tuyapi@noreply.github.com&gt;; 
抄送: "所念皆星河"<1905616103@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [codetheweb/tuyapi] Can&#39;t get tuya-cli wizard to work (#432)





 
Same issue here:
 TypeError: Promise.all called on non-object     at all (<anonymous&gt;)     at Function.any (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:29:9)     at any (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/index.js:16:9)     at list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:70:35)     at processTicksAndRejections (internal/process/task_queues.js:97:5) There was an issue fetching that device. Make sure your account is linked and the ID is correct.  
I have 2 devices listed online, pasting either device's ID # into the CLI results in this same error.

**Comment by JeremyKennedy** [comment]
I have the same issue. Here are some other reports of this: https://github.com/TuyaAPI/cli/issues/114, https://github.com/codetheweb/tuyapi/issues/434

I am currently using the Tuya Home Assistant integration, but would much prefer to switch to LocalTuya and ditch the cloud.

**Comment by codetheweb** [comment]
Interesting that everyone started having the same problem all of a sudden.

What's your Node.js version?

I can try removing the Promise.all polyfill that's currently there since it's built into Node now but not sure why it would start throwing errors suddenly.

**Comment by JeremyKennedy** [comment]
My Node version is v12.20.2, running on Ubuntu 20.04.2. This is my first time using this package, so I'm not sure if it would have worked previously for me.

**Comment by codetheweb** [comment]
Try updating to something more recent?

Not sure why that would be the cause but it's working for me on 15.0.1.

**Comment by JeremyKennedy** [comment]
Wow, I can't believe that worked. 

According to my package manager, `v12.21.0` is the latest, and I still have the issue. Since I don't want to mess with my system's Node version, I ran a Docker container using Node 15: `sudo docker run -it --rm node:15 npx -p @tuyapi/cli tuya-cli wizard` and surprisingly, this worked. Then, I tested using the same method, except using Node 12 in Docker. This gives me the same issue. So, it is definitely related to the Node version (and not something else with my system).

I did some testing using different Node versions in Docker. 
- 11 - broken
- 12 - broken
- 13 - broken
- 14 - broken
- 15 - working

I will note that earlier today I had success using the method [here](https://github.com/rospogrigio/localtuya/issues/387), but I prefer the wizard, so I'm glad we have this workaround using Docker.

**Comment by Alfiegerner** [comment]
Doing a little debug and found that if I edit wizard.js and put credentials in there it works fine:

```
        const savedAPIKey = 'my_api_key';
        const savedAPISecret = 'my_secret';
        const savedAPIRegion = 'us';

```

**Comment by codetheweb** [comment]
🤔 there must have been a dependency change somewhere because I'm pretty sure not everyone was using v15 before...

**Comment by Feeeeeelix** [comment]
Same problem🤔

**Comment by Feeeeeelix** [comment]
> Wow, I can't believe that worked.
> 
> According to my package manager, `v12.21.0` is the latest, and I still have the issue. Since I don't want to mess with my system's Node version, I ran a Docker container using Node 15: `sudo docker run -it --rm node:15 npx -p @tuyapi/cli tuya-cli wizard` and surprisingly, this worked. Then, I tested using the same method, except using Node 12 in Docker. This gives me the same issue. So, it is definitely related to the Node version (and not something else with my system).
> 
> I did some testing using different Node versions in Docker.
> 
> * 11 - broken
> * 12 - broken
> * 13 - broken
> * 14 - broken
> * 15 - working
> 
> I will note that earlier today I had success using the method [here](https://github.com/rospogrigio/localtuya/issues/387), but I prefer the wizard, so I'm glad we have this workaround using Docker.

thank you so much!!!

**Comment by rawbear** [comment]
Same problem and the Docker solution worked.

**Comment by codetheweb** [comment]
I'm able to reproduce the issue using Docker but not with bare metal Node.js (using nvm)... very odd.

Still investigating.

**Comment by codetheweb** [comment]
Still investigating.

https://github.com/es-shims/Promise.any/issues/10

**Comment by ljharb** [comment]
Please try with v2.0.2 of `promise.any`.

**Comment by codetheweb** [comment]
Fixed in v1.15.2 of @tuyapi/cli. Please update and try again.
