### ISSUE TITLE
Promise.all called on a non-object: tuya-cli wizard not working

### ISSUE THREAD

**Issue by gkgkgkgk** [codetheweb/tuyapi#434]
The tuya-api cli fails to fetch the device, throwing this error: 
`There was an issue fetching that device. Make sure your account is linked and the ID is correct.`

```
TypeError: Promise.all called on non-object
    at all (<anonymous>)
    at Function.any (C:\Users\gkepe\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\promise.any\implementation.js:29:9)
    at any (C:\Users\gkepe\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\promise.any\index.js:16:9)
    at list (C:\Users\gkepe\AppData\Roaming\npm\node_modules\@tuyapi\cli\lib\wizard.js:70:35)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

Running on windows, followed steps 1-5 in the setup page.

Thanks!

**Comment by codetheweb** [comment]
Consolidating issues, please follow https://github.com/codetheweb/tuyapi/issues/432 for updates.
