### ISSUE TITLE
Error: No permissions. This API is not subscribed.

### ISSUE THREAD

**Issue by lironas** [codetheweb/tuyapi#475]
I'm getting this error

can you help?

[
  Error: No permissions. This API is not subscribed.
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  Error: No permissions. This API is not subscribed.
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  Error: No permissions. This API is not subscribed.
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  Error: No permissions. This API is not subscribed.
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
]

**Comment by codetheweb** [comment]
It seems they changed the way permissions work again; I opened a ticket.

**Comment by codetheweb** [comment]
I just updated the setup instructions, hopefully that helps: https://github.com/codetheweb/tuyapi/commit/6f0bf1024bc39c2caf07a17391ac609a6fcf8e2e

**Comment by Taylor-Carnell** [comment]
@codetheweb 
I had this same error. 
It seems you now need to go to Cloud>Projects>"MyProject">API then click "Go to authorize", "Select API", then click subscribe on "Smart Home Devices Management" in the dropdown.
It takes you to the page for the API, click subscribe again, then click "basic edition" and "buy now" (basic edition is free).
If the "Smart Home Devices Management" API is not listed under Cloud>Projects>"MyProject">API, you need to click "New Authorization" and select it.
Works once you have done this.

**Comment by evandavey** [comment]
Followed the additional steps above i.e. authorizing "Smart Home Devices Management" but still getting the permissions error.

**Comment by codetheweb** [comment]
@evandavey is your error message the same as the one here? https://github.com/codetheweb/tuyapi/issues/485

If so, please join that issue. Otherwise please create a new issue and post the full error.

**Comment by codetheweb** [comment]
Moving discussion to https://github.com/codetheweb/tuyapi/issues/485 since errors are identical.
