### ISSUE TITLE
Setup using CLI-Wizard is throwing an error

### ISSUE THREAD

**Issue by kirkbrownOK** [codetheweb/tuyapi#48]
This work is most impressive. Unfortunately for me I'm having an issue with the SETUP process. I got my API Key and Secret from tuya. Then I attempted the CLI WIZARD steps provided. My wifi password is a 10 digit string and as a result, I believe it is failing a password validity check. This is the error message I get. 

[21:51:50] openhabian@openHABianPi:/etc/openhab2/scripts$ tuya-cli link-wizard
? Make the indicator light on your device flash.
                For most devices, this means holding down the main button.
                Press return when it's blinking. Yes
? What's your WiFi called? skittles
? What's the password for your WiFi? [hidden]
? How many devices do you want to link? 1
? Do you want to save devices that are successfully linked? Yes
✖ Device(s) failed to be registered!
Error: Invalid WiFi password
    at TuyaLink.registerSmartLink (/usr/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/lib/link.js:64:11)
    at TuyaLinkWizard.linkDevice (/usr/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/index.js:93:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by codetheweb** [comment]
Sorry about that. I think what's happening is that the CLI library I'm using is typecasting it to a Number rather than the expected String. As the number's larger than 64 (maximum allowed length), it then fails the validity test. 

I'll take a closer look tonight.

**Comment by codetheweb** [comment]
@kirkbrownOK should be working now.  Update the CLI tool with `npm i @tuyapi/cli@1.0.1 -g` and please try again.

**Comment by RR2301** [comment]
Hi 
I have been struggling for while to control my tuya smart plug though njstuya api file.. I have followed the exact steps mentioned in git hub repository.

Appreciate your help in resolving the below issue. 

`
$sudo node njstuya -ip 192.168.XX.XX -id adkepsh9u7acdv98h -key w4duxc9vkrsajt9gy7 OFF
`

/etc/openhab2/scripts/node_modules/node-forge/lib/aes.js:203
    var len = tmp.length();
                  ^

TypeError: tmp.length is not a function
    at forge.aes.Algorithm.initialize (/etc/openhab2/scripts/node_modules/node-forge/lib/aes.js:203:19)
    at new forge.cipher.BlockCipher (/etc/openhab2/scripts/node_modules/node-forge/lib/cipher.js:118:18)
    at Object.forge.cipher.createCipher (/etc/openhab2/scripts/node_modules/node-forge/lib/cipher.js:42:10)
    at new TuyaCipher (/etc/openhab2/scripts/node_modules/tuyapi/lib/cipher.js:13:30)
    at new TuyaDevice (/etc/openhab2/scripts/node_modules/tuyapi/index.js:43:24)
    at Object.<anonymous> (/etc/openhab2/scripts/njsTuya/scripts/njstuya.js:26:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)

**Comment by RR2301** [comment]
@codetheweb 
Thanks for your quick reply.
In spite of using the correct ID format and CLI package @tuyapi/cli  I am getting the below error. 
`
pi@raspberrypi:/etc/openhab2/scripts $ tuya-cli set --id 0120057360019492b55d --key w4duxc9v3vkrsajt8gy7 --set false
`
/usr/local/lib/node_modules/@tuyapi/cli/node_modules/node-forge/lib/aes.js:203
    var len = tmp.length();
                  ^

TypeError: tmp.length is not a function
    at forge.aes.Algorithm.initialize (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/node-forge/lib/aes.js:203:19)
    at new forge.cipher.BlockCipher (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/node-forge/lib/cipher.js:118:18)
    at Object.forge.cipher.createCipher (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/node-forge/lib/cipher.js:42:10)
    at new TuyaCipher (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/lib/cipher.js:13:30)
    at new TuyaDevice (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:43:24)
    at parseConfig (/usr/local/lib/node_modules/@tuyapi/cli/lib/control.js:24:10)
    at Object.set (/usr/local/lib/node_modules/@tuyapi/cli/lib/control.js:50:15)
    at Command.program.command.description.option.option.option.option.option.action.options (/usr/local/lib/node_modules/@tuyapi/cli/cli.js:59:11)
    at Command.listener (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)

Note : I retrieve the ID  of a smart plug from  tuya app installed in my phone. Is there any other way to fetch the ID. I tried tuya-cli link-wizard but it did not work.

**Comment by codetheweb** [comment]
@RR2301 that looks like the right ID but still the wrong format for the key.  Try following [this guide](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md) to get the ID and key.

**Comment by RR2301** [comment]
I already tried following the guide several times but landing at the same place :(. Moreover '  $tuya-cli list-app ' command  doesn't return anything.

Also, I wanted to know - I already have got the key pair from tuya and I can pull the device ID from TUya app on smart phone. What else I am missing.

can there be a simple way to resolve the issue?  'sudo tuya-cli link-wizard' is faling almost all the time. There much be something wrong with an environment.


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by codetheweb** [comment]
There's no other way to acquire the IDs and keys other than (a) performing a MITM attack on your phone (what `tuya-cli list app` and the Android method do) or (b) generating an official linking token using Tuya's API and transmitting it to the device.  The first method is relatively easy, the second is not and now costs money after Tuya has updated their API.

All that to say that you have to follow the guide to get the parameters.  What's not working with `list-app`?  Do you have an iPhone?  Did you trust the certificate (different than installing the certificate)?

**Comment by RR2301** [comment]
@Max

Tuya-cli list app command is working fine. I have also trusted the certificate on my IPhone. I can see the transaction in charles proxy app on my desktop.

[Image]

As you see the screenshot above. ‘Tuya-cli link-wizard’ is not registering the device.

Could you please let me know, if I am missing any step.

Rgds/


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by codetheweb** [comment]
People have been having issues with `link-wizard`.  If the `list-app` command is working, you should be able to get your parameters from that.  If not, you said you can see traffic in Charles so I'd advise looking through those requests to get the ID and key.

**Comment by RR2301** [comment]
Yes , I am able to get the ApiKey and Api secret

Now how do use this to toggle the switch ON/OFF

As I understood from  GIt repository - we have two options

Option 1 : pi@raspberrypi:/etc/openhab2/scripts $ tuya-cli set --id 0120057360019492b55d --key w4duxc9v3vkrsajt8gy7 --set false

Option 2:node   njstuya.js -ip xx -id xx OFF butnwhen run the command I get an error tmp.length is not a function
at forge.aes.Algorithm.initialize

Let me know if there are any other option available.

Rgds/Rajeev

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by codetheweb** [comment]
Does the `tuya-cli set` work?  You can do `--set false` and `--set true` to respectively turn your device off and on.

The other option would be to write your own script file in NodeJS using TuyAPI.

**Comment by RR2301** [comment]
Yes I tried tuya-cli set got an error.

'
pi@raspberrypi:/etc/openhab2/scripts $ sudo tuya-cli set --id 0120057360019492b55d --key w4duxc9v3vkrsajt8gy7 --set false
'
Please find the error response below.


usr/local/lib/node_modules/@tuyapi/cli/node_modules/node-forge/lib/aes.js:203
    var len = tmp.length();
                  ^

TypeError: tmp.length is not a function
    at forge.aes.Algorithm.initialize (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/node-forge/lib/aes.js:203:19)
    at new forge.cipher.BlockCipher (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/node-forge/lib/cipher.js:118:18)
    at Object.forge.cipher.createCipher (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/node-forge/lib/cipher.js:42:10)
    at new TuyaCipher (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/lib/cipher.js:13:30)
    at new TuyaDevice (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:43:24)
    at parseConfig (/usr/local/lib/node_modules/@tuyapi/cli/lib/control.js:24:10)
    at Object.set (/usr/local/lib/node_modules/@tuyapi/cli/lib/control.js:50:15)
    at Command.program.command.description.option.option.option.option.option.action.options (/usr/local/lib/node_modules/@tuyapi/cli/cli.js:59:11)
    at Command.listener (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by codetheweb** [comment]
Hmm, your ID looks good but the key still looks too long (should be 16 characters).  Could you post a link to the device that you bought?  And how did you get those parameters?

Also, please make sure that your Node version is >=6.0.0.  You can check with `node -v`.

**Comment by RR2301** [comment]
Here is he link the smart plug I bought from amazon.

https://www.amazon.com/MartinJerry-Compatible-Devices-required-installation/dp/B071Z94F4F

Rgds/Rajee

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by codetheweb** [comment]
Your device looks fine, I have a very similar one.  Can you please check your Node version?  Did you get the above parameters with `tuya-cli list-app`?

**Comment by RR2301** [comment]
Here is the node version
pi@raspberrypi:/etc/openhab2/scripts $ node -v
v11.0.0

tuya-cli list-app return no value  however tuya-cli list throw below result.

'
pi@raspberrypi:/etc/openhab2/scripts $ tuya-cli list-app
pi@raspberrypi:/etc/openhab2/scripts $ tuya-cli list
{ apiKey: 'w4duxc9v3vkrsajt8gy7',
  apiSecret:
   '4j5jkjxrtd87v75dwparnx35ygcu87m84j5jkjxrtd87v75dwparnx35ygcu87m84j5jkjxrtd87v75dwparnx35ygcu87m8' }

'

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by codetheweb** [comment]
The `list` command just outputs saved API keys and device parameters.

Do you have an iOS or Android smartphone?

**Comment by RR2301** [comment]
Hi please find the additional details. I tried running both the proxies. Tuya—Cli list-app and Charles.

I got the traffic response only in Charles. Attaching the screenshot for your reference. I couldn’t  able to find the tuya Key details. Am I doing any thing wrong?

[Image]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by codetheweb** [comment]
It looks like it's only capturing the CONNECT requests for some reason, not actual traffic.  Did you [trust the certificate](https://support.apple.com/en-nz/HT204477)?
