### ISSUE TITLE
data scrabled

### ISSUE THREAD

**Issue by promy** [codetheweb/tuyapi#511]
I received a new controller unit from my heat pump reseller.
With the old one tuyapi worked without a problem. However when i reran the wizard and tried the example (with updated virtual id) i get the following error:

`Connected to device!
Data from device: �O�M*<�R�|3�eSbc_��*MR}���
/root/tuyapi/test/tuyapi_test.js:31
  console.log(`Boolean status of default property: ${data.dps['1']}.`);
                                                             ^

TypeError: Cannot read property '1' of undefined
    at TuyaDevice.device.on.data (/root/tuyapi/test/tuyapi_test.js:31:62)
    at TuyaDevice.emit (events.js:198:13)
    at TuyaDevice._packetHandler (/root/node_modules/tuyapi/index.js:627:12)
    at packets.forEach.packet (/root/node_modules/tuyapi/index.js:507:43)
    at Array.forEach (<anonymous>)
    at Socket.client.on.data (/root/node_modules/tuyapi/index.js:503:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)` 

Any idea's what could be wrong? Seems like the data is scrabled or so.
The app from tuya on android works without a problem.

**Comment by promy** [comment]
Never mind...found the error: not only the virtual id was changed, but also the key...
