### ISSUE TITLE
Error: GET_TOKEN_FAILED 2007, your ip(120.84.*.246) cross-region access is not allowed

### ISSUE THREAD

**Issue by Karry-ok** [codetheweb/tuyapi#568]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Debug Output**
Post the output of your program/app/script when run with the `DEBUG` environment variable set to `*`.  Example: `DEBUG=* node test.js`.  Copy the output and paste it below (in between the code fences):

```

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - OS Version [e.g. 22]
 - Node Version [output of `node -v`]

**Additional context**

**Comment by codetheweb** [comment]
Can you please fill out the above template?

**Comment by tmkasun** [comment]
I'm too getting this error

```
Error: GET_TOKEN_FAILED 2007
```

```
✖ Device(s) failed to be registered!
Error: GET_TOKEN_FAILED 2007, your ip(112.135.209.226) cross-region access is not allowed
    at TuyaOpenApiClient.<anonymous> (/home/user/.nvm/versions/node/v16.13.1/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:123:35)
    at step (/home/user/.nvm/versions/node/v16.13.1/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:52:23)
    at Object.next (/home/user/.nvm/versions/node/v16.13.1/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:33:53)
    at fulfilled (/home/user/.nvm/versions/node/v16.13.1/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
