### ISSUE TITLE
Cross Region access not allowed

### ISSUE THREAD

**Issue by gogreenpower** [codetheweb/tuyapi#574]
**Describe the bug**
Following the [guide ](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#linking-a-tuya-device-with-smart-link) results in an error:

`✖ Device(s) failed to be registered!
Error: your ip(XXX.XXX.XXX.XXX) cross-region access is not allowed
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**To Reproduce**

on step 7: 

On the command line, run tuya-cli link --api-key <your api key> --api-secret <your api secret> --schema <your schema/Channel ID> --ssid <your WiFi name> --password <your WiFi password> --region us. For the region parameter, choose the two-letter country code from us, eu, and cn that is geographically closest to you.

**Expected behavior**
My tuya device to be linked.

**Debug Output**
`✖ Device(s) failed to be registered!
Error: your ip(XXX.XXX.XXX.XXX) cross-region access is not allowed
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

```

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS Lite
 - OS Version: Buster
 - Node Version: v10.24.1

**Additional context**

**Comment by Apollon77** [comment]
is this still relevant?
