### ISSUE TITLE
SyntaxError: Unexpected token { when running tuya-cli wizard

### ISSUE THREAD

**Issue by DAC324** [codetheweb/tuyapi#596]
When running `tuya-cli wizard` as per instructions in `Setup.md`, I get 
```
# tuya-cli wizard
/usr/lib/node_modules/@tuyapi/cli/lib/list-app.js:85
						} catch {
						        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/@tuyapi/cli/cli.js:11:17)
# 
```
What am I doing wrong here?

**Comment by Apollon77** [comment]
Your nodejs version is too old... all current/LTS versions (12+) support this! Just older not

**Comment by DAC324** [comment]
Thanks a lot! Had to upgrade NodeRed to the current version:
```
# npm install -g node-red@3.0.2
```
Now, `tuya-cli wizard` also works as expected.
