### ISSUE TITLE
Error: GET_TOKEN_FAILED 1114, your ip(xxx.xxx.xxx.xxx) don't have access to this API

### ISSUE THREAD

**Issue by timo12357** [codetheweb/tuyapi#620]
Hi
tuya-cli link --api-key MYKEYDELETED --api-secret MYSECRET --schema MYSCHEMA --ssid MYSSID --password MYPASSWORD --region eu

Results in:

✖ Device(s) failed to be registered!
Error: GET_TOKEN_FAILED 1114, your ip(xxx.xxx.xxx.xxx) don't have access to this API
    at TuyaOpenApiClient.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:123:35)
    at step (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:52:23)
    at Object.next (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:33:53)
    at fulfilled (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

tuya-cli wizard lists devices as it should

Help

**Comment by timo12357** [comment]
Solution: This was an authentication error. I used wrong Key ans Secret.
