### ISSUE TITLE
Trouble accessing 3.4(?) Bluetooth disk light on 3.3 Gateway.

### ISSUE THREAD

**Issue by nospam2k** [codetheweb/tuyapi#661]
Using the default asynchronous example with:

```javascript
const device = new TuyAPI({
  gwID: 'xxxxxxxxxxxxxxxxxx',
  id: 'xxxxxxxxxxxxxxxxxxxx',
  key: 'xxxxxxxxxxxxxxxx'
});
```
I get:
```
  TuyAPI Finding missing IP undefined or ID ebbccf813e4cd72f4bngiq +0ms
  TuyAPI Received UDP message. +4s
  TuyAPI UDP data: +2ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     ip: '192.168.0.185',
  TuyAPI     gwId: 'eb40d3fd3f4705e9acidjt',
  TuyAPI     active: 2,
  TuyAPI     ablilty: 0,
  TuyAPI     encrypt: true,
  TuyAPI     productKey: 'keyyuwcn59gwsrr8',
  TuyAPI     version: '3.3'
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 19,
  TuyAPI   sequenceN: 0
  TuyAPI } +0ms
  TuyAPI Received UDP message. +223ms
  TuyAPI RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 258. Received 262
  TuyAPI     at boundsError (node:internal/buffer:88:9)
  TuyAPI     at Uint8Array.readInt32BE (node:internal/buffer:484:5)
  TuyAPI     at MessageParser.parsePacket (/Users/david/src/node/my_tuya/node_modules/tuyapi/lib/message-parser.js:216:36)
  TuyAPI     at MessageParser.parseRecursive (/Users/david/src/node/my_tuya/node_modules/tuyapi/lib/message-parser.js:286:25)
  TuyAPI     at MessageParser.parse (/Users/david/src/node/my_tuya/node_modules/tuyapi/lib/message-parser.js:307:17)
  TuyAPI     at Socket.<anonymous> (/Users/david/src/node/my_tuya/node_modules/tuyapi/index.js:985:26)
  TuyAPI     at Socket.emit (node:events:520:28)
  TuyAPI     at UDP.onMessage [as onmessage] (node:dgram:944:8) +1ms
  TuyAPI UDP data: +1ms
  TuyAPI undefined +0ms
/Users/david/src/node/my_tuya/node_modules/tuyapi/index.js:994
      const thisID = dataRes.payload.gwId;
                             ^

TypeError: Cannot read properties of undefined (reading 'payload')
    at Socket.<anonymous> (/Users/david/src/node/my_tuya/node_modules/tuyapi/index.js:994:30)
    at Socket.emit (node:events:520:28)
    at UDP.onMessage [as onmessage] (node:dgram:944:8)

Node.js v22.5.1
```

**Comment by nospam2k** [comment]
Here is my fix. I may have missed this documented somewhere:

```javascript
    // Need to set cid to the node id of the device connected to the gateway.
   // This info is found where you get the local key.
    status = await device.set({dps: 1, cid: '0020', set: false});
```
