### ISSUE TITLE
TypeError: this is not a typed array

### ISSUE THREAD

**Issue by orizzle** [codetheweb/tuyapi#8]
Running your example code from console in Ubuntu:

$ node ./tuya_test
/home/oriz/node_modules/tuyapi/index.js:55
  const thisData = Buffer.from(JSON.stringify(requests[this.type].status.command));
                          ^

TypeError: this is not a typed array.
    at Function.from (native)
    at TuyaDevice.getStatus.callback [as getStatus] (/home/oriz/node_modules/tuyapi/index.js:55:27)
    at Object.<anonymous> (/home/oriz/tuya_test:10:6)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Please advise?

**Comment by orizzle** [comment]
Solved my own problem.  Was using an old version of nodejs.  For anyone reading, follow this guide:

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
