### ISSUE TITLE
Linking devices fails on RasPI

### ISSUE THREAD

**Issue by DBa2016** [codetheweb/tuyapi#98]
**Describe the bug**
After installation, when starting "tuya-cli list-app", an error is issued by AnyProxy - "You can run 'anyproxy-ca' to generate one root CA and then re-run this command", then several unhandled promises are reported and nothing else happens.

**To Reproduce**
Try to link devices following https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md steps 1-3. Step 3 produces the above error.
Environment: raspbian stretch, most recent (Oct 2018) on a Raspberry Pi 3B.

**Expected behavior**
Setup as described in SETUP.md

**Desktop (please complete the following information):**
 - OS: raspbian 
 - OS Version stretch, most recent (Oct 2018)
 - Node Version v11.0.0

**Comment by codetheweb** [comment]
You're right, sorry about that.  I guess I just generated it in the beginning and forgot about that step.

As a temporary fix, I updated the setup instructions for installing AnyProxy and generating the certificate.  But I'll take a look at this some point and see if it's possible to generate the certificate in `tuya-cli`.

**Comment by flashbackpa** [comment]
**Describe the bug**

After installation, when starting "tuya-cli list-app", error appears:

root@a0d7b954-nodered:/opt$ tuya-cli list-app
(node:1025) UnhandledPromiseRejectionWarning: RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at Object.<anonymous> (/usr/lib/node_modules/@tuyapi/cli/node_modules/brotli/build/encode.js:21:207)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/lib/node_modules/@tuyapi/cli/node_modules/brotli/compress.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
(node:1025) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**To Reproduce**

Try to link devices following https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md steps 1-3. Step 3 produces the above error.
Environment: hass.io on a Raspberry Pi 3B.

**Expected behavior**
Setup as described in SETUP.md

**Desktop**

OS: hass.io
OS Version 90.2
Node Version v10.14.2

**Comment by codetheweb** [comment]
I'm guessing that error is related to free memory space @flashbackpa, check free memory with `htop` and/or increase swap space.

**Comment by flashbackpa** [comment]
@codetheweb thank you, it was enough to reboot to solve the problem ! :)

**Comment by codetheweb** [comment]
Glad you got it working.
